### ISSUE TITLE
License needed

### ISSUE THREAD

**Issue by olorton** [phpoxford/spires#1]
Obviously open source, but which?

**Comment by ascii-soup** [comment]
The "You are not allowed to use this for anything unless you've contributed
or have a prior agreement with the phpoxford management committee" license.

Or MIT, I guess, whichever.

**Comment by garethellis36** [comment]
DBAD
http://www.dbad-license.org/

**Comment by olorton** [comment]
MIT :+1:

**Comment by liquorvicar** [comment]
DBAD :+1:

**Comment by olorton** [comment]
Whatever we choose, this should have the same license as https://github.com/phpoxford/spires-irc/issues/1

I'm locking this thread as we should only have the conversation in one place. (I know it was me that opened both issues). Ping me on irc if you want this unlocking with reasons or at least the promise of more beer.
