### ISSUE TITLE
Hook up issues, pull requests and merges to IRC

### ISSUE THREAD

**Issue by olorton** [phpoxford/spires#19]
Since we're being pretty active right now, let's hook this up to IRC. Does anyone know how to do it?

If not I'm happy to research and sort it out.

**Comment by olorton** [comment]
I've just worked out how to do it, I'll do it.

**Comment by olorton** [comment]
I'd also like to have this work for issue creation.

**Comment by garethellis36** [comment]
Can this be done without a bot? Seems more like a plugin that we should prioritize.

**Comment by olorton** [comment]
Fixed
