### ISSUE TITLE
Review Freenode rules

### ISSUE THREAD

**Issue by garethellis36** [phpoxford/spires#9]

**Comment by garethellis36** [comment]
[FAQ](http://freenode.net/faq.shtml) reviewed. Would be worth registering ourselves as a group to properly own #phpoxford if it hasn't already been done. @olorton to check. Other than that, nothing of note. Will review [policies](http://freenode.net/policy.shtml) next.

**Comment by garethellis36** [comment]
No issues in the policies.

**Comment by liquorvicar** [comment]
@garethellis36 Do you do any real work?
